version: 1.0.{build}

# branches to build
branches:
  # whitelist
  only:
    - master

# clone directory
clone_folder: c:\samp-roleplay

# install (after repo cloning)
install:
  - git submodule update --init --recursive

# custom build scripts
build_script:
  - cmd: c:\samp-roleplay\pawno\pawncc.exe "gamemodes\roleplay.pwn" -o"gamemodes\roleplay.amx" -i"./pawno/include" "-;" "-("
