#if defined _INCLUDED_TEXTDRAWS_HOUSES
    #endinput
#endif
#define _INCLUDED_TEXTDRAWS_HOUSES

//-----------------------------------------------------

CreateOfferListTextDraws() {
    Textdraw0 = TextDrawCreate(320.000000, 353.000000, "~n~~n~~n~");
    TextDrawAlignment(Textdraw0, 2);
    TextDrawBackgroundColor(Textdraw0, 255);
    TextDrawFont(Textdraw0, 1);
    TextDrawLetterSize(Textdraw0, 0.500000, 5.000000);
    TextDrawColor(Textdraw0, 255);
    TextDrawSetOutline(Textdraw0, 0);
    TextDrawSetProportional(Textdraw0, 1);
    TextDrawSetShadow(Textdraw0, 1);
    TextDrawUseBox(Textdraw0, 1);
    TextDrawBoxColor(Textdraw0, 252651584);
    TextDrawTextSize(Textdraw0, 180.000000, 650.000000);
    TextDrawSetSelectable(Textdraw0, 0);

    Textdraw1 = TextDrawCreate(320.000000, 354.000000, "~n~");
    TextDrawAlignment(Textdraw1, 2);
    TextDrawBackgroundColor(Textdraw1, 255);
    TextDrawFont(Textdraw1, 1);
    TextDrawLetterSize(Textdraw1, 0.800000, 0.000000);
    TextDrawColor(Textdraw1, -1);
    TextDrawSetOutline(Textdraw1, 0);
    TextDrawSetProportional(Textdraw1, 1);
    TextDrawSetShadow(Textdraw1, 1);
    TextDrawUseBox(Textdraw1, 1);
    TextDrawBoxColor(Textdraw1, 64);
    TextDrawTextSize(Textdraw1, 0.000000, 650.000000);
    TextDrawSetSelectable(Textdraw1, 0);

    Textdraw2 = TextDrawCreate(628.000000, 357.000000, " ~n~ >>~n~ ~n~");
    TextDrawAlignment(Textdraw2, 2);
    TextDrawBackgroundColor(Textdraw2, 32);
    TextDrawFont(Textdraw2, 3);
    TextDrawLetterSize(Textdraw2, 0.230000, 3.200000);
    TextDrawColor(Textdraw2, -1);
    TextDrawSetOutline(Textdraw2, 1);
    TextDrawSetProportional(Textdraw2, 1);
    TextDrawUseBox(Textdraw2, 1);
    TextDrawBoxColor(Textdraw2, 842170448);
    TextDrawTextSize(Textdraw2, 160.000000, 21.000000);
    TextDrawSetSelectable(Textdraw2, 1);

    Textdraw3 = TextDrawCreate(9.000000, 357.000000, " ~n~ <<~n~ ~n~");
    TextDrawAlignment(Textdraw3, 2);
    TextDrawBackgroundColor(Textdraw3, 32);
    TextDrawFont(Textdraw3, 3);
    TextDrawLetterSize(Textdraw3, 0.219999, 3.200000);
    TextDrawColor(Textdraw3, -1);
    TextDrawSetOutline(Textdraw3, 0);
    TextDrawSetProportional(Textdraw3, 1);
    TextDrawSetShadow(Textdraw3, 1);
    TextDrawUseBox(Textdraw3, 1);
    TextDrawBoxColor(Textdraw3, 842170448);
    TextDrawTextSize(Textdraw3, 90.000000, 25.000000);
    TextDrawSetSelectable(Textdraw3, 1);

    Textdraw4 = TextDrawCreate(320.000000, 447.000000, "~n~");
    TextDrawAlignment(Textdraw4, 2);
    TextDrawBackgroundColor(Textdraw4, 255);
    TextDrawFont(Textdraw4, 1);
    TextDrawLetterSize(Textdraw4, 0.800000, 1.299999);
    TextDrawColor(Textdraw4, -1);
    TextDrawSetOutline(Textdraw4, 0);
    TextDrawSetProportional(Textdraw4, 1);
    TextDrawSetShadow(Textdraw4, 1);
    TextDrawUseBox(Textdraw4, 1);
    TextDrawBoxColor(Textdraw4, 64);
    TextDrawTextSize(Textdraw4, 0.000000, 640.000000);
    TextDrawSetSelectable(Textdraw4, 0);

    Textdraw5 = TextDrawCreate(0.000000, 267.000000, " ");
    TextDrawBackgroundColor(Textdraw5, 0);
    TextDrawFont(Textdraw5, 5);
    TextDrawSetPreviewModel(Textdraw5, 17699)TextDrawSetPreviewRot(Textdraw5, -4.000000, 0.000000, 71.000000, 0.899999)TextDrawSetPreviewVehCol(Textdraw5, 0, 0)TextDrawLetterSize(Textdraw5, 0.500000, 1.000000);
    TextDrawColor(Textdraw5, -1);
    TextDrawSetOutline(Textdraw5, 0);
    TextDrawSetProportional(Textdraw5, 1);
    TextDrawSetShadow(Textdraw5, 1);
    TextDrawTextSize(Textdraw5, 120.000000, 120.000000);
    TextDrawSetSelectable(Textdraw5, 0);
    TextDrawSetPreviewModel(Textdraw5, 17699);
    TextDrawSetPreviewRot(Textdraw5, -4.000000, 0.000000, 71.000000, 0.899999);
    TextDrawSetPreviewVehCol(Textdraw5, 0, 0);

    Textdraw6 = TextDrawCreate(93.400001, 360.000000, "~n~~n~~n~~n~~n~~n~~n~~n~Kaufen - ~g~$290.000");
    TextDrawAlignment(Textdraw6, 2);
    TextDrawBackgroundColor(Textdraw6, 255);
    TextDrawFont(Textdraw6, 2);
    TextDrawLetterSize(Textdraw6, 0.200000, 1.000000);
    TextDrawColor(Textdraw6, -1);
    TextDrawSetOutline(Textdraw6, 0);
    TextDrawSetProportional(Textdraw6, 1);
    TextDrawSetShadow(Textdraw6, 1);
    TextDrawUseBox(Textdraw6, 1);
    TextDrawBoxColor(Textdraw6, 100);
    TextDrawTextSize(Textdraw6, 90.000000, 100.000000);
    TextDrawSetSelectable(Textdraw6, 1);

    Textdraw7 = TextDrawCreate(48.000000, 360.000000, " ");
    TextDrawAlignment(Textdraw7, 2);
    TextDrawBackgroundColor(Textdraw7, 0);
    TextDrawFont(Textdraw7, 5);
    TextDrawSetPreviewModel(Textdraw7, 3614)TextDrawSetPreviewRot(Textdraw7, 0.000000, 0.000000, 0.000000, 1.000000)TextDrawSetPreviewVehCol(Textdraw7, 0, 0)TextDrawLetterSize(Textdraw7, 0.500000, 1.000000);
    TextDrawColor(Textdraw7, -1);
    TextDrawSetOutline(Textdraw7, 0);
    TextDrawSetProportional(Textdraw7, 1);
    TextDrawSetShadow(Textdraw7, 1);
    TextDrawTextSize(Textdraw7, 70.000000, 70.000000);
    TextDrawSetSelectable(Textdraw7, 0);
    TextDrawSetPreviewModel(Textdraw7, 3614);
    TextDrawSetPreviewRot(Textdraw7, 0.000000, 0.000000, 0.000000, 1.000000);
    TextDrawSetPreviewVehCol(Textdraw7, 0, 0);

    Textdraw8 = TextDrawCreate(202.800003, 360.000000, "~n~~n~~n~~n~~n~~n~~n~~n~Kaufen - ~g~$290.000");
    TextDrawAlignment(Textdraw8, 2);
    TextDrawBackgroundColor(Textdraw8, 255);
    TextDrawFont(Textdraw8, 2);
    TextDrawLetterSize(Textdraw8, 0.200000, 1.000000);
    TextDrawColor(Textdraw8, -1);
    TextDrawSetOutline(Textdraw8, 0);
    TextDrawSetProportional(Textdraw8, 1);
    TextDrawSetShadow(Textdraw8, 1);
    TextDrawUseBox(Textdraw8, 1);
    TextDrawBoxColor(Textdraw8, 100);
    TextDrawTextSize(Textdraw8, 90.000000, 100.000000);
    TextDrawSetSelectable(Textdraw8, 1);

    Textdraw9 = TextDrawCreate(167.399993, 360.000000, " ");
    TextDrawAlignment(Textdraw9, 2);
    TextDrawBackgroundColor(Textdraw9, 0);
    TextDrawFont(Textdraw9, 5);
    TextDrawSetPreviewModel(Textdraw9, 3614)TextDrawSetPreviewRot(Textdraw9, 0.000000, 0.000000, 0.000000, 1.000000)TextDrawSetPreviewVehCol(Textdraw9, 0, 0)TextDrawLetterSize(Textdraw9, 0.500000, 1.000000);
    TextDrawColor(Textdraw9, -1);
    TextDrawSetOutline(Textdraw9, 0);
    TextDrawSetProportional(Textdraw9, 1);
    TextDrawSetShadow(Textdraw9, 1);
    TextDrawTextSize(Textdraw9, 70.000000, 70.000000);
    TextDrawSetSelectable(Textdraw9, 0);
    TextDrawSetPreviewModel(Textdraw9, 3614);
    TextDrawSetPreviewRot(Textdraw9, 0.000000, 0.000000, 0.000000, 1.000000);
    TextDrawSetPreviewVehCol(Textdraw9, 0, 0);

    Textdraw10 = TextDrawCreate(312.200012, 360.000000, "~n~~n~~n~~n~~n~~n~~n~~n~Kaufen - ~g~$290.000");
    TextDrawAlignment(Textdraw10, 2);
    TextDrawBackgroundColor(Textdraw10, 255);
    TextDrawFont(Textdraw10, 2);
    TextDrawLetterSize(Textdraw10, 0.200000, 1.000000);
    TextDrawColor(Textdraw10, -1);
    TextDrawSetOutline(Textdraw10, 0);
    TextDrawSetProportional(Textdraw10, 1);
    TextDrawSetShadow(Textdraw10, 1);
    TextDrawUseBox(Textdraw10, 1);
    TextDrawBoxColor(Textdraw10, 100);
    TextDrawTextSize(Textdraw10, 90.000000, 100.000000);
    TextDrawSetSelectable(Textdraw10, 1);

    Textdraw11 = TextDrawCreate(276.799987, 360.000000, " ");
    TextDrawAlignment(Textdraw11, 2);
    TextDrawBackgroundColor(Textdraw11, 0);
    TextDrawFont(Textdraw11, 5);
    TextDrawSetPreviewModel(Textdraw11, 3614)TextDrawSetPreviewRot(Textdraw11, 0.000000, 0.000000, 0.000000, 1.000000)TextDrawSetPreviewVehCol(Textdraw11, 0, 0)TextDrawLetterSize(Textdraw11, 0.500000, 1.000000);
    TextDrawColor(Textdraw11, -1);
    TextDrawSetOutline(Textdraw11, 0);
    TextDrawSetProportional(Textdraw11, 1);
    TextDrawSetShadow(Textdraw11, 1);
    TextDrawTextSize(Textdraw11, 70.000000, 70.000000);
    TextDrawSetSelectable(Textdraw11, 0);
    TextDrawSetPreviewModel(Textdraw11, 3614);
    TextDrawSetPreviewRot(Textdraw11, 0.000000, 0.000000, 0.000000, 1.000000);
    TextDrawSetPreviewVehCol(Textdraw11, 0, 0);

    Textdraw12 = TextDrawCreate(421.600006, 360.000000, "~n~~n~~n~~n~~n~~n~~n~~n~Kaufen - ~g~$290.000");
    TextDrawAlignment(Textdraw12, 2);
    TextDrawBackgroundColor(Textdraw12, 255);
    TextDrawFont(Textdraw12, 2);
    TextDrawLetterSize(Textdraw12, 0.200000, 1.000000);
    TextDrawColor(Textdraw12, -1);
    TextDrawSetOutline(Textdraw12, 0);
    TextDrawSetProportional(Textdraw12, 1);
    TextDrawSetShadow(Textdraw12, 1);
    TextDrawUseBox(Textdraw12, 1);
    TextDrawBoxColor(Textdraw12, 100);
    TextDrawTextSize(Textdraw12, 90.000000, 100.000000);
    TextDrawSetSelectable(Textdraw12, 1);

    Textdraw13 = TextDrawCreate(386.200012, 360.000000, " ");
    TextDrawAlignment(Textdraw13, 2);
    TextDrawBackgroundColor(Textdraw13, 0);
    TextDrawFont(Textdraw13, 5);
    TextDrawSetPreviewModel(Textdraw13, 3614)TextDrawSetPreviewRot(Textdraw13, 0.000000, 0.000000, 0.000000, 1.000000)TextDrawSetPreviewVehCol(Textdraw13, 0, 0)TextDrawLetterSize(Textdraw13, 0.500000, 1.000000);
    TextDrawColor(Textdraw13, -1);
    TextDrawSetOutline(Textdraw13, 0);
    TextDrawSetProportional(Textdraw13, 1);
    TextDrawSetShadow(Textdraw13, 1);
    TextDrawTextSize(Textdraw13, 70.000000, 70.000000);
    TextDrawSetSelectable(Textdraw13, 0);
    TextDrawSetPreviewModel(Textdraw13, 3614);
    TextDrawSetPreviewRot(Textdraw13, 0.000000, 0.000000, 0.000000, 1.000000);
    TextDrawSetPreviewVehCol(Textdraw13, 0, 0);

    Textdraw14 = TextDrawCreate(531.000000, 360.000000, "~n~~n~~n~~n~~n~~n~~n~~n~Kaufen - ~g~$290.000");
    TextDrawAlignment(Textdraw14, 2);
    TextDrawBackgroundColor(Textdraw14, 255);
    TextDrawFont(Textdraw14, 2);
    TextDrawLetterSize(Textdraw14, 0.200000, 1.000000);
    TextDrawColor(Textdraw14, -1);
    TextDrawSetOutline(Textdraw14, 0);
    TextDrawSetProportional(Textdraw14, 1);
    TextDrawSetShadow(Textdraw14, 1);
    TextDrawUseBox(Textdraw14, 1);
    TextDrawBoxColor(Textdraw14, 100);
    TextDrawTextSize(Textdraw14, 90.000000, 100.000000);
    TextDrawSetSelectable(Textdraw14, 1);

    Textdraw15 = TextDrawCreate(495.600006, 360.000000, " ");
    TextDrawAlignment(Textdraw15, 2);
    TextDrawBackgroundColor(Textdraw15, 0);
    TextDrawFont(Textdraw15, 5);
    TextDrawSetPreviewModel(Textdraw15, 3614)TextDrawSetPreviewRot(Textdraw15, 0.000000, 0.000000, 0.000000, 1.000000)TextDrawSetPreviewVehCol(Textdraw15, 0, 0)TextDrawLetterSize(Textdraw15, 0.500000, 1.000000);
    TextDrawColor(Textdraw15, -1);
    TextDrawSetOutline(Textdraw15, 0);
    TextDrawSetProportional(Textdraw15, 1);
    TextDrawSetShadow(Textdraw15, 1);
    TextDrawTextSize(Textdraw15, 70.000000, 70.000000);
    TextDrawSetSelectable(Textdraw15, 0);
    TextDrawSetPreviewModel(Textdraw15, 3614);
    TextDrawSetPreviewRot(Textdraw15, 0.000000, 0.000000, 0.000000, 1.000000);
    TextDrawSetPreviewVehCol(Textdraw15, 0, 0);
}